### ISSUE TITLE
Prevent analog date range from going into the past month until after 10th of current month

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/analog-forecast-gui-dash#4]
To prevent a user getting an Interal server error due to the analog data being unavailable, we need to prevent the calendar from going beyond two months past until after the 10th of the month when new data will be downloaded.

For example, today is August 3rd, we would want the end date to go back to June 30th at maximum. On August 11th, all of July is available for use in the calendar.

**Comment by brucecrevensten** [comment]
Closed in previous commits.
